# This is a sample build configuration for .NET Core.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: microsoft/dotnet:2.1-sdk

pipelines:
  default:
    - step:
        name: Install NodeJS
        script:
          - echo "Installing NodeJS..."
          # set up node
          - export NODE_VERSION=8.9.4
          - export NODE_DOWNLOAD_SHA=21fb4690e349f82d708ae766def01d7fec1b085ce1f5ab30d9bda8ee126ca8fc
          - curl -SL "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz" --output nodejs.tar.gz \
             && echo "$NODE_DOWNLOAD_SHA nodejs.tar.gz" | sha256sum -c - \
             && tar -xzf "nodejs.tar.gz" -C /usr/local --strip-components=1 \
             && rm nodejs.tar.gz \
             && ln -s /usr/local/bin/node /usr/local/bin/nodejs
    - step:
        caches:
          - dotnetcore
        script: # Modify the commands below to build your repository.
          # - export PROJECT_NAME=name.sln
          # - export TEST_NAME=yourTestName
          - dotnet --info
          - dotnet restore
          - dotnet build
          # dotnet build ./src/Presentation/AspNetBase.Presentation.App/AspNetBase.Presentation.csproj
          # - dotnet test $TEST_NAME
