# This is a sample build configuration for .NET Core.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: vmandic/dotnet21-node894:v1

pipelines:
  default:
    - step:
        name: Build dotnetcore sln
        caches:
          - dotnetcore
        script: 
          - echo "Building dotnet solution..."
          - dotnet --info
          - dotnet restore
          - dotnet build
